return {
  Base = {
    Paths = {
      base = "Data/",
      binary = "Binary/",
      script = "Scripts/",
      shader = "Shaders/",
      texture = "Textures/",
    },
  },
  Graphics = {
    Particle = {
      renderNormals = false,
    },
    Terrain = {
      calculateNormals = false,
      cdlodBlendEnd = 0.775,
      cdlodBlendStart = 0.625,
      chunksPerTile = 64,
      lodBias = 8,
      lruGracePeriod = 500,
      lruTargetSize = 2000,
      numberOfGeneratorThreads = 4,
      prebakeCompressionType = "BC1",
      prebakeSize = 256,
      prebakeUseCompression = true,
      preloadThreshold = 1.1,
      terrainGenerator = "TG_CPU_MT",
      terrainSize = 16384,
      tessellationEnabled = true,
      tileSize = 64,
      useAdaptiveTessellation = false,
      useSuperThreading = false,
      useTriplanar = true,
    },
    benchmarkDimensions = { 1920, 1080,},
    cameraEyeStart = { 10, 25, 10,},
    enableScattering = true,
    enableShadows = false,
    frameInterval = 0,
    multisampleLevel = 1,
    multisampleQuality = 0,
    useSoftwareRenderer = false,
    vsyncEnabled = false,
  },
  SIE = {
    dtCtrlArrowsToggleVisible = true,
    dtMinimumColumnWidth = 70,
    enableRenderer = true,
    floatingFormSize = { 1600, 850,},
    iffAutoTemplateApply = true,
    iffAutoTemplateNamingOn = true,
    iffShowCSharpHelper = false,
    logDeleteOldLogs = true,
    logNumLinesDisplayed = 50,
    palAlwaysDarkenNumbers = false,
    palAlwaysShowNumbers = true,
    palShowEdges = false,
    repoAutoplayAudio = true,
    repoFileSelectAutoplayAudio = true,
    repoInTab = false,
    sndAutoplayAudio = true,
    wsAllowCellEditing = false,
    wsNodeRadiusMax = 2048,
    wsRadiusAroundSnapshotNodes = 35,
    wsShowRadiusAroundSnapshotNodes = false,
  },
  SWB = {
    openSnapshotOnLoad = false,
  },
  SWG = {
    additionalOverrideDirectories = {},
    baseDirectory = "C:/Users/jojoj/OneDrive/Desktop/_swg/exe/win32/",
    repositoryScript = "precu.lua",
    repositoryScriptPath = "Config/Repository/",
    repositoryStoresHistory = true,
    repositoryStoresNames = true,
    suppressWarningsOnMissingFiles = false,
    useFileOverrides = false,
  },
  Shared = {
    defaultAppearance = "defaultappearance.apt",
    defaultShader = "defaultshader.sht",
    defaultSnapshot = "corellia.ws",
    defaultTerrain = "corellia.trn",
    defaultTexture = "defaulttexture.dds",
  },
}