sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
script:
  - git clone https://bitbucket.org/swgathrawn/udplibrary.git externals/udplibrary
  - mkdir build
  - cd build
  - cmake .. && make

notifications:
  email:
    recipients: builds@eb2.co
    on_success: change
    on_failure: always

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
            - libboost-dev
            - libboost-program-options-dev
            - libsqlite3-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
