# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Build Java

on:
  push:
    branches: [ master ]
    paths:
      - '**.java'
  pull_request:
    branches: [ master ]
    paths:
      - '**.java'

jobs:
  build:      
    runs-on: ubuntu-latest    
          
    steps:
      ################################
      # Setup environment            #
      ################################
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.2'
          
      ################################
      # Run Linter against code base #
      ################################
      #- name: Lint Code Base
      #  uses: github/super-linter@v3
      #  env:
      #    VALIDATE_ALL_CODEBASE: false
      #    DEFAULT_BRANCH: master
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      ################################
      # Compile Java with ANT        #
      ################################
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml compile_java
